# Site settings
title: My Territory
index_title: Shikher Verma # same as title in index.html file, so that custom description can be set in page.html layout.
blog_title: My Territory
header-img: img/home-bg.jpg
email: root@shikherverma.com
copyright_name: ShikherVerma
description: "Online Territory of Shikher Verma"
baseurl: "" #base url is for when the site is not at the root but at some subdirectory.
url: shikherverma.com #only used in disque comments for now
github_username:  shikherverma
facebook_username:  shikherverma1
email_username:  root@shikherverma.com
# used to estimate reading time
wpm: 180

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
port: 8888

# jekyll-paginate
paginate: 5
paginate_path: blog/page:num

# gem dependencies
gems: [jekyll-paginate, jekyll-feed]
